@Restaurants.API_HostAddress = https://localhost:7278

@token =CfDJ8Ke8ZSo6zXFLle5l90OVR_uwraYSGzclQoGWpLTP9NbNP9u0PB0mhAzMPalO2A8Ajirb6cUkoacmdEb7vzdvqyCFy8fFOW6NKPQN0ZHP-Ma2p_Eewl6FGdj7axd5h8P6j0r99adEid8hOzAWOFs0jhwoZFzLgQV6ssJEv4Lzqqnx21XI_U44QFhELAEIF83ubS6_ixKPS_E4jYyEzUaptbZciDDmRMcIIJy1xVw1-yx550ckrt2Q2cZdL-Umg5brcmNreVk-Av0ka7WA5bwWuFZ2HgiMuZoHq0xISt_EFBbMEO7v9Ca4L1nIa8vqj-e4By3hCBXJd-_Lxjzqa2D9vV9Nfy4PQhViwv07SQRzxwo-gucEzcCVotbQz8NGVjZgRBp89j8Pl2cy3ujkg5aMtl3jux3H4AN3dGoo7qnl6rA_Ri0-b-AS4UzCMUE_h49CcJS9-Y0fDe-IRYSrFvi3zKFlRoXgyloL4xJ7AOs2sBzlTngeSz3IJ6_s-zXkKA0PBOcJZ_l6fns0Ltp8HX2GN6WsEXthB--PuwH5X3BDNInOuIEdz0ajfesWoyUUSXfPZ-ejr2MufQWEef12-GXhV5DbpW0YV4EnSzBIMzr2q3h8af65dH8wY9V41-o2nsGPJQxLWjWfDGPrpVzYYICfmHyHSPek5v7rfFPbrF2YOUA18Sf7KB1GNT7ik6XOdmHJmodhR3T5w3-7ymDlpfGL_yvH1Nh8lY1L1w2fLsYoHRhx_mQErpuDCEQRSjwATcjTlBonbHBnfW5tF-Gx6TTR9RMp-ap6dTQ33tIHyris0XiDBII2hVFWhhp46yT6GlWxLIVj2hG5h7kIPUWnwTmEKQ6i8lnM3kolwxdikgrPe2rGgB0x_LsypB41AofQfEgmKw
###


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type:application/json


{
  "Name": "Restaurant whit Owner",
  "Description": "4 restaurand cozy restaurant indian serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@test.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
  
}





###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

###




###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "beach restaurant",
  "Description": "This is a sample restaurant description and updated.",
  "HasDelivery": false
}


###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 13.99,
  "KiloCalories": 750
}


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/2

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/399/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "testuser6@test.com",
    "password": "Password6!"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}

###


PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality":"French",
  "DateOfBirth": "2010-01-01"
}

###
