@Restaurants.API_HostAddress = https://localhost:7278



###


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type:application/json
{
  "Name": "Tasty Bites",
  "Description": "A cozy restaurant serving a variety of dishes.",
  "Category": "Indian",
  "ContactEmail": "info@hotmail.com",
  "ContactNumber": "dd",
  "PostalCode": "10-311"
}



###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/7
Content-Type:application/json
{
  "Name": "Tasto taylan",
  "Description": "crazy dishes.",
  "Category": "Indian",
  "ContactEmail": "info2@hotmail.com",
  "ContactNumber": "dd",
  "PostalCode": "10-311"
}


###
